# Example Travis config. See the entire example: https://github.com/JonathanPorta/ci-build

language: csharp
solution: ./Brain-Control.sln
sudo: required

# Already by default.
#mono:
#  -latest

addons:
  sonarcloud:
    organization: "graygzou-github"
    token:
      secure: ${SONAR_TOKEN}

before_install:
  - chmod a+x ./Scripts/*.sh

install:
  - ./Scripts/install.sh
  # NUnit test
  - nuget install NUnit.Runners -Version 2.6.4 -OutputDirectory testrunner

script:
  # Run customs tests.
  - ./Scripts/run-tests.sh
  - ./Scripts/build.sh

  # NUnit tests
  - mono ./testrunner/NUnit.Runners.2.6.4/tools/nunit-console.exe ./BrainControl.Tests/bin/Release/BrainControl.Tests.dll

after_success:
  - sonar-scanner
  # Not working right now. Need to add something that feed him with reports.
  # Unity Test Runner ? OpenCover ? ...
  #- bash <(curl -s https://codecov.io/bash)

cache:
  directories:
    - '$HOME/.sonar/cache'

notifications:
  email:
    recipients:
      - boiron.greg@gmail.com
    on_success: change # Default: change. Can be replace by never.
    on_failure: always # Default: always
