# Example Travis config. See the entire example: https://github.com/JonathanPorta/ci-build

language: objective-c
dist: trusty
sudo: required

osx_image: xcode61
rvm:
  - 2.1.2
install:
  - ./Scripts/install.sh
script:
  - ./Scripts/build.sh
  - sonar-scanner -X
after_success:
  # Not working right now. Need to add something that feed him with reports.
  # Unity Test Runner ? OpenCover ? ...
  - bash <(curl -s https://codecov.io/bash)

addons:
  sonarcloud:
    organization: "graygzou-github"
    token:
      secure: "BIxzLzkiQO9j4HvPjUkOUkg0yyUCu90wk7vCSl2jAhVZRBFpw5vgIGfFEpjGTd3EN5PXhqEIcEFGMJsvu2dtIl7AkUJ4H3rhrArouJkGKgUe1r2SAYHoNR0NuzLDOgocO6Yz7FUrg9LAAbu5xEnrOb6tJPFzxefXkyQsLhS+6icVDdvB3Tk5VEY/71LzJW5L7tDg7cs1WuqBk5iO04YEXezT+3FsStaV+/SrSAL9dfRiBVeqGAg4R8D33ISGSQsPfCsl09BdeXRGph2b6k2pF90zNeWXtLln4mx1xmKaioSOcCkXPjfzbzwHFkvMa3PUCwD8pT5KP3sssZG7vvUPTc/yW06NIG857dTNhG+3/Jpu4YeBkZPR51Gd3lxiNQUHQ4JhAgCe/Tw7cG3dcl/TK/e04wWZPEyMZBjNeihmP5jgMdOITp3mE89D+cMLot9EZ8eK24C4vtwRDsrtu4shzi57qtDeD3nLCL2nlTC5Jz/qaQe+cwqI5rgFmizigxXasCto5p4CzeKcstLQEeivzeF//0e4LvQ0Puw5mubKjpwECdhKf8Wb2pmXRPlv4EeNhy7e9ZsKuLTHsqzVJWrdrSgza0D++k54V49Ea5lWtrWyyO/xF16agIeiOSNBdP0kDx4fiKczWpo7wBV2HV0Vn6j+OpEQLjbqNEXL7L5IpvQ="

notifications:
  email:
    recipients:
      - boiron.greg@gmail.com
    on_success: never # Default: change
    on_failure: always # Default: always
