# Example Travis config. See the entire example: https://github.com/JonathanPorta/ci-build

language: objective-c
osx_image: xcode61
rvm:
  - 2.1.2
install:
  - ./Scripts/install.sh
script:
  - ./Scripts/build.sh
after_success:
  - ./Scripts/sonarcloud.sh
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    recipients:
      - boiron.greg@gmail.com
    on_success: never # default: change
    on_failure: always # default: always
