# Example Travis config. See the entire example: https://github.com/JonathanPorta/ci-build

language: objective-c
dist: trusty

osx_image: xcode61
rvm:
  - 2.1.2
install:
  - ./Scripts/install.sh
script:
  - ./Scripts/build.sh
  - sonar-scanner -X
after_success:
  # Not working right now. Need to add something that feed him with reports.
  # Unity Test Runner ? OpenCover ? ...
  - bash <(curl -s https://codecov.io/bash)

addons:
  sonarcloud:
    organization: "graygzou-github"
    token:
      secure: "aa6Fd6CYcH/xlgLtu2l7lgLEm8+EOFrqawCqqF1nTn8YzOVFFl1NYZYqC1T7igNPXzCucQZ0vnFI8HU5QsZFHUrMnax554pIvJrh8wG60Hwi+6B84oIcBndKqB/TTt0Dp1sC637VVzwhjFRqL8J4LL3ML6P2lhaLPPniyvDERBHi4T+cbiDb15wT34JHJOA6ilVVz7/7SwiMFrbpW2GTDewmcSEnPkK+LYX+JS7HvJPmXa9rWIkPyQH1QfoTmQ1J2Op1l7BeNIEWvPukb3PsGOJlBFuk9jnGq9KB6MM/GLFVmigLEmNIzrox6l+1IiOTkPnEnZgAHlPdSfYDzRRH3TMADP6UIZrSbevcofVeCnKELSvHv9mywla+iN2COselmBse6Fp3WOQqMcDkUQiMLdyGlL3K8TyLFfIRyqRiUWnswyj0l+Moho428Y6c6BGx3mwHA6QTehF4qtQHR2L44zmtSm+wDB2zCazW5sM2S6dl/G2ji48U1SheWVuu09EkT/OxUz98fYSiQ2ok/rUzYedBcUrDHyRYLNXytKuxgje3QlaUgvVpCvOh4c2UGKanv8seoWmHnHnpY74Jn5y36ClFHJ44E6slvi0DuQRIM0UQRd5y/sgnbdvZMVfEaVp9hvggYqwOcZuDQWNOJel7jkFysDHPmTJy6Q1fIuuC484="
      
notifications:
  email:
    recipients:
      - boiron.greg@gmail.com
    on_success: never # Default: change
    on_failure: always # Default: always
