# Example Travis config. See the entire example: https://github.com/JonathanPorta/ci-build

language: objective-c
dist: trusty
sudo: required

addons:
  sonarcloud:
    organization: "graygzou-github"
    token:
      secure: ${SONAR_TOKEN}


osx_image: xcode9.3
rvm:
  - 2.2
install:
  - ./Scripts/install.sh
script:
  - ./Scripts/build.sh
  - sonar-scanner
after_success:
  # Not working right now. Need to add something that feed him with reports.
  # Unity Test Runner ? OpenCover ? ...
  - bash <(curl -s https://codecov.io/bash)

#cache:
#  directories:
#    - '$HOME/.sonar/cache'

notifications:
  email:
    recipients:
      - boiron.greg@gmail.com
    on_success: never # Default: change
    on_failure: always # Default: always
