# Example Travis config. See the entire example: https://github.com/JonathanPorta/ci-build

language: csharp
solution: "Brain-Control.sln"
osx_image: xcode7.3
dist: trusty
sudo: required

# Already by default.
#mono:
#  -latest

addons:
  sonarcloud:
    organization: "graygzou-github"
    token:
      secure: ${SONAR_TOKEN}

before_install:
  - chmod a+x ./Scripts/*.sh

install:
  - ./Scripts/install.sh

script:
  - ./Scripts/run-tests.sh
  - ./Scripts/build.sh

after_success:
  - sonar-scanner
  # Not working right now. Need to add something that feed him with reports.
  # Unity Test Runner ? OpenCover ? ...
  - bash <(curl -s https://codecov.io/bash)

cache:
  directories:
    - '$HOME/.sonar/cache'

notifications:
  email:
    recipients:
      - boiron.greg@gmail.com
    on_success: change # Default: change. Can be replace by never.
    on_failure: always # Default: always
